version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck

formatters:
  enable:
    - gofmt

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
